let request = {
  query: "jarat_kifejtes_text_jsonC",
  datum: "2024-05-19",
  start_ls_id: 0,
  start_ls_name: "Balatonfűzfő",
  stop_ls_id: 0,
  stop_ls_name: "Veszprém",

  // not required apparently
  fieldvalue: {
    runcount: 2,
    runs: {
      "0": {
        "0": 2,
        "1": 1,
        "2": 221,
        "3": 27500395,
        "4": 583,
        "5": 27500396,
        "6": 314,
        "7": 320,
        "8": 6000,
        "9": 1596,
        "10": 4488722,
        "11": 2,
        "12": 100000,
        "13": 76880,
        "14": 1596,
        "15": "9000",
        "16": "9720",
        "17": false,
        "18": false,
        "19": 191110,
        "20": 573672,
        "21": 187637,
        "22": 571508,
        "23": "Balatonfűzfő vá.",
        "24": "Balatonalmádi vá.",
        "25": "",
        "26": 0,
        "27": 0,
        "28": 0,
        "29": "naponta",
        "30": 0,
        "31": "",
        "32": 0,
        "33": 0,
        "34": 0,
        "35": 0,
        "36": "",
        "37": "",
        "38": "9720",
        "39": 12,
        "40": 12,
        "41": -1,
        "42": 0,
        "43": 0,
        "44": 0,
        "45": "VESz",
        "46": 0,
        "47": 0,
        "48": 0,
        "49": false,
        "50": 278895645,
        "51": "Balatonfűzfő",
        "52": "Balatonalmádi",
        "53": "",
        "54": "",
        "55": 3,
        "56": "Walking",
        "57": "",
        "58": "",
        "59": "",
        "60": "",
        "61": "",
        "62": "",
      },
      "1": {
        "0": 2,
        "1": 2,
        "2": 583,
        "3": 1418,
        "4": 1176,
        "5": 1817,
        "6": 330,
        "7": 357,
        "8": 12900,
        "9": 37991,
        "10": 3514980,
        "11": 1,
        "12": 100000,
        "13": 188641,
        "14": 37991,
        "15": "7333",
        "16": "302",
        "17": false,
        "18": false,
        "19": 187863,
        "20": 571538,
        "21": 195202,
        "22": 563939,
        "23": "Balatonalmádi, autóbusz-állomás",
        "24": "Veszprém, autóbusz-állomás",
        "25": "Veszprém - Balatonalmádi",
        "26": 0,
        "27": 0,
        "28": 0,
        "29": "naponta",
        "30": 0,
        "31": "",
        "32": 0,
        "33": 0,
        "34": 0,
        "35": 0,
        "36": "",
        "37": "",
        "38": "7333",
        "39": 8,
        "40": 20,
        "41": 450,
        "42": 0,
        "43": 0,
        "44": 0,
        "45": "",
        "46": 225,
        "47": 45,
        "48": 0,
        "49": false,
        "50": 278895645,
        "51": "Balatonalmádi",
        "52": "Veszprém",
        "53": "",
        "54": "",
        "55": 0,
        "56": "Walking",
        "57": "",
        "58": "",
        "59": "",
        "60": "",
        "61": "",
        "62": "",
      },
    },
  },
  nativeData: [
    {
      Count: 2,
      Sequence: 1,
      DepartureSettle: 221,
      DepartureStation: 27500395,
      ArrivalSettle: 583,
      ArrivalStation: 27500396,
      DepartureTime: 314,
      ArrivalTime: 320,
      Distance: 6000,
      RestrictionId: 1596,
      RunId: 4488722,
      NetworkId: 2,
      WalkDistance: 100000,
      LrId: 76880,
      RdId: 1596,
      Domain_code: "9000",
      Number: "9720",
      DepartureOutside: false,
      ArrivalOutside: false,
      DepEovX: 191110,
      DepEovY: 573672,
      ArrEovX: 187637,
      ArrEovY: 571508,
      DepStationName: "Balatonfűzfő vá.",
      ArrStationName: "Balatonalmádi vá.",
      DomainCompanyName: "",
      Prebuy: 0,
      // ... 2 more zeroes
      Explanation: "naponta",
      // zero
      // empty string
      // 4 zeroes
      // 2 empty strings
      LocalDomainCode: "9720",
      DepartureSeqnr: 12,
      ArrivalSeqnr: 12,
      Fare: -1,
      // 3 zeroes
      RunCategory: "VESz",
      // 3 zeroes
      // One of these false values
      Heke: false,
      Bube: false,
      local_pass_useable: false,
      bkk_pass_useable: false,

      PeakMemory: 278895645,
      FromSettle: "Balatonfűzfő",
      ToSettle: "Balatonalmádi",
      // 2 empty strings
      ChangeTime: 3,
      ChangeMode: "Walking",
      // 6 empty strings



      chargeInfo: {
        parts: [
          {
            order: 1,
            purposeOfJourneyPartition: "",
            fromStopPoint: 27500395,
            toStopPoint: 27500396,
            distanceInMeter: 6000,
            fareClass: "secondClass",
            facilities: [],
            zones: [],
          },
        ],
        facilities: ["cyclesAllowed", "train"],
        common_zone: "",
        productCategory: null,
      },
      
      GlobalPassUsage: "County",
      FareSumExtra: 0,
      FareExtra: 0,
      FareSeatRes: 0,
      FareFifty: 0,
      FareNinty: 0,
      TicketType: "OneRideOnly",
      LinkStation: 0,
      Hitcount: 46,
      ChangeRoute: "",
      ChangeLs: 1418,
      FromPs: 27000361,
      ToPs: 27000362,
      InternalId: 156543,
      FromBay: "",
      ToBay: "",
      Owner: 27,
      FirstClassFee: 0,
      OwnerName: "MÁV",
      DatabaseVersion: 1715969883,
      BikeCarriage: 0,
      BikeForbidden: 0,
      BikeRestricted: 1,
      BikeSeatTicket: 0,
      BkszDomainCode: "0",
      BufeCar: 0,
      Detour: 0,
      DiningCar: 0,
      DirectCarriage: 0,
      DisabledPeople: 0,
      FirstClass: 0,
      HighSpeed: 0,
      Internet: 0,
      JourneyName: "",
      LowFloor: 0,
      NoSuperCharge: 1,
      Premium: 0,
      Remark: "",
      RunType: "",
      SeatTicketCompulsory: 0,
      Superior: 0,
      SupplementaryTicketCompulsory: 0,
      WheelChairNoLift: 0,
      WheelChairWithLift: 1,
      Wifi: 0,
      CountyPass: "Veszprém",
      GlobalPass: "Veszprém",
      LongName: "9720",
      NumberType: "TrainNumber",
      ShortName: "9720",
      TransportMode: "vehicles.train",
      News: { Title: "", Url: "" },
    },
    {
      Count: 2,
      Sequence: 2,
      DepartureSettle: 583,
      DepartureStation: 1418,
      ArrivalSettle: 1176,
      ArrivalStation: 1817,
      DepartureTime: 330,
      ArrivalTime: 357,
      Distance: 12900,
      RestrictionId: 37991,
      RunId: 3514980,
      NetworkId: 1,
      WalkDistance: 100000,
      LrId: 188641,
      RdId: 37991,
      Domain_code: "7333",
      Number: "302",
      DepartureOutside: false,
      ArrivalOutside: false,
      DepEovX: 187863,
      DepEovY: 571538,
      ArrEovX: 195202,
      ArrEovY: 563939,
      DepStationName: "Balatonalmádi, autóbusz-állomás",
      ArrStationName: "Veszprém, autóbusz-állomás",
      DomainCompanyName: "Veszprém - Balatonalmádi",
      // 3 zeroes
      Explanation: "naponta",
      // zero
      // empty string
      // 4 zeroes
      // 2 empty strings
      LocalDomainCode: "7333",
      DepartureSeqnr: 8,
      ArrivalSeqnr: 20,
      Fare: 450,

      // 3 zeroes - sum extra, extra, seat res?
      FareExtra: 0,
      FareSumExtra: 0,
      FareSeatRes: 0,

      RunCategory: "",
      FareFifty: 225,
      FareNinty: 45,
      // zero
      // false
      PeakMemory: 278895645,
      FromSettle: "Balatonalmádi",
      ToSettle: "Veszprém",
      // 2 empty strings
      ChangeTime: 0,
      ChangeMode: "Walking",
      // 6 empty strings

      // ZEROES LEFT:
      Prebuy: 0,
      LinkStation: 0,
      FirstClassFee: 0,
      BikeCarriage: 0,
      BikeForbidden: 0,
      BikeRestricted: 0,
      BikeSeatTicket: 0,
      BufeCar: 0,
      Detour: 0,
      DiningCar: 0,
      DirectCarriage: 0,
      DisabledPeople: 0,
      FirstClass: 0,
      HighSpeed: 0,
      Internet: 0,
      LowFloor: 0,
      Premium: 0,
      SeatTicketCompulsory: 0,
      Superior: 0,
      SupplementaryTicketCompulsory: 0,
      WheelChairNoLift: 0,
      WheelChairWithLift: 0,
      Wifi: 0,

      // EMPTY STRINGS LEFT
      ToBay: "",
      JourneyName: "",
      Remark: "",
      ChangeRoute: "",
      RunType: "",

      // FALSE LEFT
      Heke: false,
      local_pass_useable: false,
      bkk_pass_useable: false,
      Bube: false,


      chargeInfo: {
        parts: [
          {
            order: 1,
            purposeOfJourneyPartition: "",
            fromStopPoint: 1418,
            toStopPoint: 1817,
            distanceInMeter: 14700,
            fareClass: "secondClass",
            facilities: [],
            zones: [],
          },
        ],
        facilities: ["animalsAllowed", "baggageStorage", "coach"],
        common_zone: "",
        productCategory: null,
      },
      GlobalPassUsage: "County",
      
      TicketType: "OneRideOnly",
      Hitcount: 46,
      FromPs: 575240,
      ToPs: 575054,
      InternalId: 58342,
      FromBay: "2",
      Owner: 43,
      OwnerName: "Volánbusz",
      DatabaseVersion: 1715969883,
      BkszDomainCode: "0",
      NoSuperCharge: 1,
      CountyPass: "Veszprém",
      GlobalPass: "Veszprém",
      LongName: "7333/302",
      NumberType: "TripNumber",
      ShortName: "7333",
      TransportMode: "vehicles.bus",
      News: { Title: "", Url: "" },
    },
  ],
};

const RUNS = [
  "Count",
  "Sequence",
  "DepartureSettle",
  "DepartureStation",
  "ArrivalSettle",
  "ArrivalStation",
  "DepartureTime",
  "ArrivalTime",
  "Distance",
  "RestrictionId",
  "RunId",
  "NetworkId",
  "WalkDistance",
  "LrId",
  "RdId",
  "Domain_code",
  "Number",
  "DepartureOutside",
  "ArrivalOutside",
  "DepEovX",
  "DepEovY",
  "ArrEovX",
  "ArrEovY",
  "DepStationName",
  "ArrStationName",
  "DomainCompanyName",
  "TODO-0",
  "TODO-0",
  "TODO-0",
  "Explanation",
  "TODO-0",
  "TODO-str",
  "TODO-0",
  "TODO-0",
  "TODO-0",
  "TODO-0",
  "TODO-str",
  "TODO-str",
  "LocalDomainCode",
  "DepartureSeqnr",
  "ArrivalSeqnr",
  "Fare",
  // TODO: Order of these
  "FareExtra",
  "FareSumExtra",
  "FareSeatRes",

  "RunCategory",
  "FareFifty",
  "FareNinty",
  "TODO-0",
  "TODO-false",
  "PeakMemory",
  "FromSettle",
  "ToSettle",
  "TODO-str",
  "TODO-str",
  "ChangeTime",
  "ChangeMode",
  "TODO-str",
  "TODO-str",
  "TODO-str",
  "TODO-str",
  "TODO-str",
  "TODO-str",
]
